version: "3.4"

services:
  db:
    image: database
    build:
      context: ./database
      dockerfile: ./Dockerfile
      target: development
    container_name: database
    environment:
      POSTGRES_USER: "ecdbadmin"
      POSTGRES_PASSWORD: "testP1ssW0rd"
      POSTGRES_DB: "ecdatastorage"
    networks:
      - ecommerce

  api:
    image: api
    build:
      context: ./api
      dockerfile: ./Dockerfile
      target: development
    container_name: api
    networks:
      - ecommerce
  
  proxy:
    image: proxy
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
      target: development
    container_name: proxy
    links:
      - "api:api"
    ports:
      - 80:80
      - 443:443
    networks:
      - ecommerce
    depends_on:
      - api

networks:
  ecommerce:
    driver: bridge
